= Food And Health Week 1 
:icons: font
:toc: left
:stem: latexmath
:numbered:
:source-highlighter: prettify
:last-update-label!:
:nofooter:

== Introduction

Around the world today, people are suffering from more diet-related diseases than ever before in recent history. 

The so-called Western diet has been <<implicated>> as the major contributor to our modern <<epidemics>> of disease.  We don't actually know what about the western diet is creating the problems but what we do know with a great deal of confidence is that populations who eat this diet which is normally defined as a diet high in meat high in processed foods with very little whole grains very little fruits and vegetables. The populations who eat that way have very high rates of <<chronic>> disease. 

When you think about the increasing rates of <<obesity>> and <<diabetes>> you could really think of it as a <<tsunami>> wave off the coast. It's <<enormous>>.  <<Physicians>> nowadays more than ever need to advise patients about food. Which foods to eat more of or less of and why. 

How to shop for, prepare, cook, enjoy healthy delicious foods. Not just nutritious fats not bio-chemistry but food.  We are living in a food environments that fails to support our health. 

Taking back the control over our food preparation is essential to our long term well-being. By examining our eating behaviors and learning the skills we need to reclaim responsibility for what's in our food, we can celebrate the foods that will protect us and bring us pleasure for the rest of our lives. 

== A <<Sociocultural>> History of Obesity

The human body runs on food. Once, food shortage was the major concern. After the Second World War, technological advances in food production led to a new <<era>> that was characterized by an <<overabundance>> of inexpensive food, and relatively little physical activity. In the decades that followed, other socio-cultural shifts continued to contribute to the changing way we ate. Women who had previously controlled most of the average family's food preparation, now enter the workforce in significant numbers. And the processed food industry began to <<capitalize>> on our need for fast convenient food. 

This meant that fewer meals for being cooked at home, and since convenient foods were generally higher in calories than home-cooked meals, the average persons caloric <<intake>> increase <<dramatically>>. 

Academic studying the <<intersection>> of food and health like Michael Pollan, have written extensively about the implications of this cultural shift on the way we eat today. 

To the extent, we <<outsource>> our food. First, we eat less healthy food, more salt, and fat, and sugar. But we also eat more food because processed food is often designed as <<snack>> food, and marketed to us as a way to eat continually through the day. 

The changes in the way, we, as a society ate led to the emergence of obesity as a recognized chronic disease with well-defined health consequences, and medical recommendations were made to try and address this growing health crisis. 

In the second half of the 20th century, a lot of attention was focused on reducing <<saturated>> fat, and total fat in our diets. And the processed food industry responded by giving us what we wanted. But, they still had a vested interest in selling their products, so they found other ways to make the reduced fat products taste good. 

One way they did this was by adding significantly more sugar, and other forms of sugar, like corn <<syrup>> to almost everything we ate. This not only made the reduced fat foods more appealing, but it also increased their shelf life. So the food industry had a huge <<incentive>> to add corn syrup, and other sweeteners to packaged foods. The resulting increase in our intake of simple sugars fueled our modern epidemics of obesity and diabetes. These shifts in our food <<consumption>> patterns have led us to a point in history where our physiological adaptation, our ability to store energy as fat, has become <<maladaptive>>. The balance between food availability and energy expenditure has been <<disrupted>>, and its left us with an <<exponential>> increase in the <<incidence>> of obesity over the past 60 years. An epidemic that the World Health Organization has labeled a worldwide public health crisis. 


== Macronutrient Structure & Metabolism

In order to survive, the human organism needs to take in oxygen, water, and food. We can survive only about three minutes without air, three days without water, and three weeks without food. Because food is so important to our survival, it's been studied extensively. And since 1827 when a British physician by the name of William Prout first proposed that humans need three macronutrients to survive, physicians, scientists, and increasingly the general public have trying to figure out exactly how much of each of these nutrients will optimize our health. 

But to some extent, the focus on nutrients rather than food has confused many people. >> And we tend to get lost in this conversation about nutrients, good and bad and it's understandable because scientists need to reduce things to a single variable to study them. And the variable in food would appear to be the nutrient. But we also have lots of studies that show that simply removing or boosting nutrients or turning them into supplements doesn't seem to work. That food is much more complicated, it's a system. >> A basic understanding of the nutrients can give us a helpful background for our discussions about food. So we'll review the nutrients and how the body uses them, but most of this course will focus on discussions about food and health. Because ultimately, people eat food, not nutrients. Dietary carbohydrates are combinations of sugar units that come in both simple and complex forms. Simple carbohydrates include the <<monosaccharides>>, or single sugar units like <<glucose>> and <<fructose>>. As well as the disaccharides, or two-sugar units like sucrose, or table sugar. Complex carbohydrates, or <<polysaccharides>>, include the dietary starches that our body can break down and digest, and also the indigestible polysaccharides that make up dietary fiber. During the process of digestion, carbohydrates are broken down and converted to glucose, which can then be metabolized by the body to produce usable energy in the form of ATP. 

If energy demands are low, glucose can be stored, and most of the time it's stored as adipose tissue. 

Dietary proteins are also broken down into their component parts, <<amino-acids>>, during the process of digestion. And these amino acids can be used to build and repair lean tissues in the body and perform many other important functions. But amino acids can also be broken down and used for energy. And if they're consumed in excess, they can contribute to fat stores in the body as well. 

Dietary fats can also be broken down into smaller components and used for energy. 

Or, they can be stored as adipose tissue, depending on our energy needs. 

Fats are the most energy dense storage form, providing nine calories of energy for every gram, and alcohol provides seven calories per gram. In contrast, carbohydrates and proteins provide only four calories per gram. This is one of the reasons we've evolved to store excess nutrients as adipose tissue, and this brings us to the underlying physiologic cause of overweight and obesity. Any calories that aren't converted into usable energy in the form of ATP are stored in the body for later use. Most of the time they're stored as adipose tissue. So disturbing the energy balance to favor energy expenditure over energy storage needs to be one of the priorities for people who are trying to lose excess weight. This can be achieved by consuming fewer calories, burning more calories through exercise, or a combination of both. But in addition, when long term health is the end goal, the quality of our food matters just as much as the number of calories we consume. Within each category of macronutrients, we need to choose foods that will support our health, rather than working against it. 

== Carbohydrate-rich Foods & the Glycemic Index

All nutrients are not created equal especially when it comes to their effect on our health. So shifting our focus from nutrients to foods can help us develop better eating habits that will support our long term health. >> Getting our head around the idea that we should be focused on the category of foods, mot nutrients, is I think very important. And I think doctors should be talking to patients about food. Even if as scientists and researchers they see through foods to nutrients. It may be a helpful way to study foods. It's not a helpful way to communicate about food. >> Let's look at an example of how focusing on nutrients rather than food can leave us confused and potentially consuming a diet that's dangerous to our health. 

In recent years, a lot of attention has been focused on the fact that many of us are eating too many carbohydrates. There are lots of popular diet trends that encourage us to drastically reduce the carbohydrates in our diet, even to the point of limiting our intake of fresh fruit. At the same time, some of these low-carb diets seem to suggest that protein and fats can be eaten freely. But a diet that's very high in animal protein and contains no whole grain or not enough fruits and vegetables could leave us with serious problems in the long run. In fact, the category carbohydrates includes a wide spectrum of foods. Some of which are really important for our health. And some of which can compromise it. Whole grains like brown rice and rolled oats are carbohydrates that provide our bodies with a usable source of energy and bound together in that very same food is a significant amount of fiber, which slows the release of glucose from that food into the bloodstream. The glycemic index of a food is the measure of the speed at which glucose is released into the blood stream after it's digested. A whole grain like brown rice or quinoa will result in a slower release of glucose and a more muted insulin response. On the other hand, a food that's high in refined carbohydrates, like white bread or soda, will lead to a more rapid release of glucose into the blood. And in response to this, the body releases a large amount of insulin, the hormone in our bodies that lowers blood sugar. Because of spike of glucose and insulin lead to less stable blood sugar levels, eating foods that are refined, especially highly processed carbohydrates, can result in an earlier return of hunger and a tendency to overeat. 

The glycemic index of a food is lower when the food contains fiber or when it's eaten in combination with protein foods or foods containing some dietary fat. 

For people who are struggling to manage their weight, or their blood sugar levels, eating foods that have a low glycemic index is especially important, but choosing low glycemic foods is generally a good idea for all us. So when we talk about dietary carbohydrates we're actually talking about a very broad family of foods. Some that can be harmful to our long term health, and some that can support it. Learning how to choose the right foods within each nutrient category is one of the keys to long term success. 

== Animal & Plant-based Proteins

Protein-rich foods, including animal and plant-based proteins can also vary enormously in their quality and their implications for our long-term health. Proteins are often said to act as building blocks for the lean tissues in our bodies. But they serve many other important functions in body regulation, supportive immune function and a variety of other roles in our physiology. There are 20 types of amino acids needed to fulfill all of these functions, but only nine of them are essential. Meaning that our bodies can't make enough of them, so we rely on getting these from our food. 

In general, animal sources of protein like fish and eggs provide all of the essential amino acids in high enough concentrations that these foods are called complete protein sources. In contrast, plant based protein sources like beans, lentils, nuts and tofu tend to be incomplete sources of protein. It might seem that since plant-based proteins are incomplete in their nutrient content that they're nutritionally inferior compared with animal-based proteins. But in fact the health benefits of substituting plant-based proteins for animal-based ones, ideally a few days a week, this far outweighs the risk of falling short on essential amino acids. Plant-based proteins can be combined with other foods to provide a complete amino acid profile. In fact, many traditional food combinations like corn and black beans or rice and lentils are based on the principal of combining complementary proteins. 

Meals that contain vegetarian sources of protein also contain more fiber and less fat, especially saturated fat, than meals that feature animal based protein. And even though saturated fat may not be as harmful as we once thought, it can still contribute to elevated levels of LDL cholesterol if we eat too much of it. So moderating our intake of red meat, for example, is still a sensible idea. In general, the typical western diet contains more animal based protein than we need to sustain good health. >> People eat lots of plant food, eat a plant based diet, tend to have much better health, and better longevity than people who eat a heavy meat diet. >> So, if you're thinking of trying a low card, high protein diet, it's important to pay attention to the kinds of proteins that are being consumed, and in what quantities. A diet high in animal protein, especially if it's poor quality animal protein, like processed meat or high fat cuts of meat, this kind of diet can be harmful to our health even if it leads to weight loss in a short term. Processed meats often contain <<nitrates>> used as a preservative, which can damage blood vessels and contribute to hardening of the arteries. These meats also tend to be very high in sodium, which can be a contributor to high blood pressure. 

The most sensible diets are usually those that encourage us to eat moderate amounts of high quality protein foods. These should come from a variety of different sources, including some fish if possible. As well as plenty of vegetarian sources of protein that are combined for completeness. 

== Dietary Fats & Their Effects on Human Health

For decades, the relationship between dietary fats and health was at the center of our attempts to understand the underlying cause of the obesity epidemic. The debates over nutrition that you will hear, should we worry about fat, should we worry about carbohydrates, is the problem lack of fiber? All these are attempts to understand what's the problem in the western diet that is the culprit. Because people like to figure that out because then you can just adjust that one thing and go on your merry way, but we haven't gotten that down yet. We don't know the answer to that question with any real confidence. >> Despite the important roles that fats play in our bodies, this entire category of food was shunned for much of the 20th century. This led to an enormous increase in the availability of fat free and reduced fat foods. But in spite of this, obesity rates continue to rise. Today, rising awareness about the difference between the so-called good fats and bad fats have allowed this important part of our food supply to make a comeback. But once again, the pendulum threatens to swing too far in the opposite direction. Dietary fats can be divided into two families, the saturated and the unsaturated fats. Saturated fats get their name from the fact that their fatty acids are saturated with hydrogen molecules. This means that they can lie flat and pack together densely so that saturated fats tend to be solids at room temperature. Animal fats, like lard and butter, are good examples. In contrast, the fatty acids that make up unsaturated fats are kinked in places where double bonds between the carbon atoms cause the chains to be less saturated with hydrogen. This also means that these fatty acids don't pack together as tightly, leaving most unsaturated fats in the liquid state at room temperature. Omega 3 fatty acids are a special kind of unsaturated fatty acid, with double bonds in specific positions of the hydrocarbon chain They're found in high concentrations in fish oil, and also to some degree in nuts, flax seeds, and other vegetable oils. Omega-3 fatty acids are the only kind of fatty acid that the human body can't make, so they're essential for our health and they need to be consumed via the food we eat. 

Unsaturated fats can be naturally occurring like the fats found in olive oil, nuts and avocados. Or they can be man made or chemically manipulated to become unsaturated. These are the fats found in some margarines and in the kinds of oils that are often used for repeated cooling and reheating in deep frying machines like the ones used in many fast food restaurants. The problem with chemically engineered unsaturated fats is that the chemical bonds between the carbon atoms are less stable, so they easily flip into a trans orientation, rather than a cis orientation. And this is where we get the name trans fats. 

Trans fats are problematic for our health because they increase the amount of LDL cholesterol in the blood and they lower the amount of HDL cholesterol, the good cholesterol in the blood. By doing this trans fats promote to formation of arterial plaques and increase the risk of heart disease. 

While saturated fats have also been shown to contribute to increases in LDL cholesterol, they haven't been shown to lower HDL cholesterol or to contribute to the development of arterial plaques as significantly as trans fats. 

So, what's the bottom line when it comes to foods that contain fat? Probably the most sensible food recommendation is this. Enjoy reasonable amounts of foods that contain mostly naturally occurring unsaturated fats like those found in olive oil, nuts and avocados. Avoid all foods containing trans fats. And limit your intake of foods like red meats that are high in saturated fats. 

== NOTES

加工肉类含有的硝酸盐对血管不好，还会导致动脉硬化。其中大量对钠元素还会导致高血压。

[bibliography]

- [[[implicated]]]  If someone or something is implicated in a crime or a bad situation, they are involved in it or responsible for it.
- [[[epidemics]]] a widespread occurrence of an infectious disease in a community at a particular time: a flu epidemic.
- [[[chronic]]] a chronic illness or chronic pain is serious and lasts for a long time. A serious illness or pain that lasts only for a short time is described as acute
- [[[obesity]]] a condition in which someone is too fat in a way that is dangerous for their health
- [[[diabetes]]] a serious medical condition in which your body does not produce enough insulin to reduce the amount of sugar in the blood
- [[[tsunami]]] a very large wave or series of waves caused when something such as an earthquake moves a large quantity of water in the sea
- [[[enormous]]] very large in size or quantity
- [[[Physicians]]] a person qualified to practise medicine, especially one who specializes in diagnosis and medical treatment as distinct from surgery. our family physician.
- [[[era]]]   a period of time that has a particular quality or character
- [[[overabundance]]]  abundance:  a very large quantity of something
- [[[capitalize]]] business to sell something you own for money that you need
- [[[intake]]]  the amount of something that you eat or drink
- [[[dramatically]]]  sudden and surprising or easy to notice
- [[[intersection]]]  a place where roads, lines etc join or cross each other
- [[[outsource]]]  If a company outsources work or things, it pays workers from outside the company to do the work or supply the things.
- [[[snack]]]  a small amount of food that you eat between meals
- [[[saturated]]]  completely filled with things or people
- [[[syrup]]]  a sweet liquid made from sugar and water
- [[[incentive]]]  something that makes you want to do something or to work harder, because you know that you will benefit by doing this
- [[[consumption]]] the use of something such as fuel or energy, or the amount that people use
- [[[maladaptive]]]
- [[[disrupted]]] interrupt
- [[[exponential]]] increasing or growing very fast
- [[[incidence]]]  the number of cases of an illness or a medical condition in a particular place, group, or situation
- [[[monosaccharides]]] 单糖
- [[[glucose]]] 葡萄糖
- [[[fructose]]] 果糖
- [[[polysaccharides]]] 多糖
- [[[amino-acids]]] 氨基酸
- [[[nitrates]]] 硝酸盐
