#+TITLE: Food and Health Week 2
#+AUTHOR: Coursera
* Why Are Highly Processed Foods Generally Less Healthy?
One of the biggest problems with the typical Western diet is the fact that much of our food is refined, or highly processed. The refining process removes important nutrients like fiber, iron and B vitamins, and this is done by food manufactures for two reasons. Firstly, it's to give the end project a softer texture, and secondly it's done to extend the shelf life of the resulting product. A heavily processed food is going to last longer on the supermarket shelf because pests, like mold for example, are less attracted to foods that are low in nutrients. A hamburger that's highly processed will spoil much more slowly than a hamburger made at home with mostly natural ingredients. 

But the question is, if highly processed food is so low in nutrients that the pests don't even want to eat it, how healthy can it be for us? 

In fact, the nutrient content of any given food is directly related to the spoil rate of that food. Foods that are very low in nutrients spoil much more slowly than foods that are rich in nutrients. >> One of the best predictors of a healthy diet is whether it was cooked by a human being or a large corporation. And the reason is that when we outsource our food preparation to big companies, they tend to cook in a certain way that isn't very healthy. They tend to use way too much salt, fat, and sugar, all of which are problematic nutrients for our health, and they tend to use the cheapest possible raw ingredients. Their business model is to start with a cheap food and process it as much as possible, make it attractive with salt, fat and sugar. >> Thinking about the nutrient density of the food is another conceptual way of making sensible food decisions. The nutrient density of a food can be thought of as the amount of nutritional value, including vitamins, minerals, and fiber, divided by the calories, or energy content, of that food. For example, a glass of soda is high in calories without providing much in the way of nutritional value. Foods that provide lots of calories with very little nutritional value are sometimes called energy dense foods, but their nutrient density is low. A bunch of fresh spinach, on the other hand, would be an example of a nutrient dense food because its nutritional value is relatively high compared to its caloric content. When people talk about fast food being cheaper than fresh food, they're often referring to the fact that the cost per calorie of highly processed food is lower than that of fresh, whole food. This is often true because highly processed food is so high in calories that the cost per calorie is relatively low. But, if we instead look at the cost of food per unit of nutrient density, then buying fewer calories of higher nutrient density food is a much better use of our food budget. 

In the midst of a serious epidemic of obesity, avoiding empty calories should be near the very top of our list of priorities. One of the reasons why highly processed food is usually higher in calories is that in order to make these products sell, significant amounts of fat, sugar, and salt are added to make the nutrient-stripped foods taste good. 

Additives like colorants, artificial flavors, stabilizers, and other preservatives, are also added to enhance packaged products and maintain the illusion that we as consumers have many choices when we walk through the supermarket aisles. 

The last thing we need to be aware of are highly processed foods that masquerade as healthy foods. These are products that have synthetic nutrients added back to them after they've been refined, and this is usually done to make the product seem healthy to the nutrition aware consumer. It's important to remember that the most nutritious foods, like broccoli, don't come in packages that tell us how healthy they are. 

* Trends in Sugar Consumption & Recommendations

Over the past 60 years, the amount of sugar consumed as part of the typical western diet has increased dramatically. Significant increases in sugar consumption have been documented in most countries where heavily processed food has become a readily available. Surprisingly, some experts estimate that only one-sixth of our sugar comes from desserts or foods that we think of as sweets. The majority of our sugar comes in the form of highly processed food and sweetened beverages. Many people are becoming aware of the need to reduce their sugar intake in order to maintain a healthy body weight. But what many people still aren't aware of, is the fact that sugar under a variety of different pseudonyms is added to so many foods that we don't expect to contain sugar. Things like packaged breads, condiments, chips, sauces, and salad dressings. In 2015, the World Health Organization release new guidelines strongly recommending that all adults and children reduce their sugar intake to less than 10% of total calories consumed. These recommendation go on to suggest that a further reduction of sugar intake to less than 5% of total calories would likely have additional health benefits. These recommendations focus on free sugars, those that are added to foods by the manufacturer, the cook, or the consumer, as well as sugars that are naturally present in honey, syrups, and fruit juices. But they don't apply to intrinsic sugars found in whole fruits and vegetables. Because the World Health Organization found no reported evidence linking the consumption of intrinsic sugars to adverse health effects. The sugar that naturally occurs in milk is also excluded from that 5%. For the average adult, consuming a 2000 calorie per day diet reducing their sugar intake to 5% would mean that ideally no more than 100 calories per day should come from free sugars. Since free sugars offer 4 calories of energy per gram this would translate into approximately 25 grams of free sugar, about 6 teaspoons. Six teaspoons seems like a generous allocation when you picture spooning it out of a sugar bowl. But when you being to look at the nutrition labels of most packaged foods, the numbers begin to add up incredibly quickly. For example, a one-half cup serving of organic granola can contain 16 grams or 4 teaspoons of sugar. If one half of a cup of regular sweetened yogurt is added to that cereal for breakfast, this can add another four teaspoons of sugar and you've already exceeded your recommended sugar intake by two full teaspoons before leaving the house. 

There's a growing consensus that we need to cut down on our sugar consumption and yet there may be a downside to vilifying sugar the way we did with the dietary fats. If we only emphasized the need to cut down on our sugar intake without simultaneously emphasizing moderation and balance in our diet as a whole, we risk a situation where fats and animal proteins are seen by the general public as free food. And the processed food industry, again steps in and super sizes. >> It's been interesting to read the research and see the shift in attention from treating fat as the evil nutrient to treating sugar as the evil nutrient. Now, we went overboard on fat. It turns out fat is not as evil as we thought and saturated fat is not necessarily the thing to worry most about in your diet. And in fact, our obsession with saturated fat led us to promote trans fat, which turned out to actually be lethal. So I'm very wary of focusing all our attention on a single nutrient. Sugar's been part of the human diet for a very long time. It's prized by people all over the world. We have evolved to like the flavor of sugar for very good reasons, but we are eating too much of it. And I think we definitely need to cut down on the amount of sugar we're eating, but I think companies need to disclose added sugar, which they don't now have to do in processed foods. I'm very concerned that sugars being added to foods that never were sweetened before. Things like bread now have sugar in them, and condiments of all kinds. because if you put more sugar in a food you will sell more of it. So we need to be conscious of it. But does it explain everything about our diet? No, it really doesn't. 

* The Case for Cooking

In many parts of the world today, but especially in the United States, the most pervasive foods in our eating environment are ones that don't necessarily support our health. One of the proposed solutions that addresses the problem in both the short and long term is a return to home cooking. What if we were to re-allocate a small amount of our time to cooking our food at home, using whole food ingredients, instead of relying so heavily on the food industry to provide us with our meals? This may be easier than it sounds, and cooking may also have some side benefits. >> What role do you think that a return to home cooking can play as we try to promote the health of our nation? >> You would think it's about the food and not the process by which it's made, but in fact the process by which the food is made has a lot to do with our health. And so we do have research that suggests that families who eat food cooked by humans are eating a better diet and are healthier as a result. But many other things follow from the process of cooking. I mean, when you cook at home you will use the best ingredients you can afford. You will keep it really simple. You don't need the food to last six months on a shelf, and the odds are, whatever you eat, it will be better than processed food. There's something about the act of cooking that enforces, without us even being conscious of it, a healthy, wholesome diet. I think it's very hard to get fat on home-cooked food. Now, the other reason though that cooking is important, is that if you cook, you will have a meal, you will sit down at a table, with other people, with family, you eat together. And that has a lot of implications for our health too. Eating alone, snacking, eating in front of the television, all these things lead to a very different kind of food consumption. >> Micheal, what advice do you have for people who say they don't know how to cook or they don't have time to cook? >> Yeah. You know I hear that a lot. People think it's the hardest thing you could ask them to do, to start cooking a little bit more. And they don't have the skills or they don't think they do. And they don't have the time. There's a lot of obstacles to cooking right now and different people have to deal with it in different ways. Some people really don't have a lot of time. And perhaps they're living alone, or perhaps both partners are working, they have a long commute. That's a legitimate challenge. My advice is two-fold. One is, involve everyone in the family in cooking. We do not bring our children into the kitchen. And that is an enormous disservice to them long-term. Take turns with your partner or share the work. A lot of the problem cooking is the work has all been dumped on one member of the family, usually the woman. And that's not fair and it's not realistic now that women are in the work force. So, sharing the work is one very important way to reduce the time burden. Another is, and I find this very useful, is give a couple hours on a Sunday to preparing food for the week. Freeze a couple things, or make a dish that is going to produce lots of leftovers. When I was researching one of my books, I was soliciting food rules. I got a letter from a doctor, a transplant cardiologist. And at his last meeting with patients, he would take out his prescription pad. And they all thought he was writing a prescription for a statin or whatever it was. But in fact, he was writing a recipe for a roast chicken. 

And on the back he turned it over and it was a recipe for making chicken tacos. And he said this is what you need, not another drug, and the idea was that if you knew how to roast a chicken, which, believe me, is not rocket science, you had the makings of three good meals. One meal rolls into the others, so you have chicken one night, and then you have tacos, chicken tacos another night and then you make a soup from the carcass. We've lost those skills, we've lost that sense of how to maximize the value of food and minimize the time investment. We erect a lot of barriers to cooking in our heads and one of the reasons I wrote cook is to help people get over those barriers and realize too that we've been kind of brainwashed to think about cooking as drudgery. It's not. It's really satisfying. 

And more satisfying the better you get at it. I mean, to handle plants and animals and fungi and to learn how to manipulate them and make something delicious and if you approach it more as a pastime and less as a chore, you will enjoy it more. And you have to realize too, that we've been getting marketing messages that are designed to get us to go out to eat or buy processed food. And those marketing messages include a very strong message that this is really hard and really boring, and it's neither of those things. People over-complicate cooking. We live in a culture that celebrates cooking, but doesn't actually do it very much. We watch it on television, we watch it in restaurants where now the kitchens are all open. And we all think that cooking means restaurant food, and it's not. That's all special occasion food. Everyday home cooking is throwing a fillet of fish on the grill or in a pan. It's taking out a box of frozen spinach. Frozen vegetables is a very healthy choice, very easy choice. You don't have to wash anything, you can use your microwave for it. You can dress it up with some garlic or olive oil or lemon juice. 

There are a lot of really satisfying meals that you can get on the table in less than a half hour. Some of us don't know how to make them, and I think that that's a tremendous problem, because the cultural transmission of knowledge about how to cook, how to be resourceful in the kitchen has been broken by a generation that's not cooking. >> By reallocating a small amount of our time and energy to the preparation of simple home cooked meals, we become empowered as we take back control over the foods we eat. Cooking is a very practical solution to our modern health challenges that can be put into action almost immediately using whatever resources are available. In addition, cooking brings us closer to food rather than seeing food as the enemy. Cooking can protect our relationship with food and it may be one of the most powerful ways to protect our long term health. 

* A Case Study: Middle-aged Pre-diabetic Man

Around the world today, more than 2 billion people are overweight or obese. Our global obesity epidemic has been described as the most significant preventable public health crisis in recent history. This 48-year-old manager of a construction firm found himself fighting an uphill battle against a disease that can effect every organ system in the human body. 

Kevin's wife had convinced him to visit their local medical clinic, because she was concerned about his weight, and the joint pain he complained of every evening after work. At the clinic, Kevin was told that his fasting blood sugar was elevated, and that he was prediabetic. His triglycerides, total cholesterol, and LDL cholesterol were also elevated and his HDL cholesterol was low. Standing 5'7" tall and weighing 180 pounds with predominant central obesity, Kevin's physician calculated a BMI of 28 kilograms per meter squared. 

Kevin was informed that he was overweight and suffering from metabolic syndrome, a collection of biochemical and physiological abnormalities associated with the development of cardiovascular disease and type two diabetes. The physician on duty advised Kevin to make some major lifestyle changes. By eating better, and getting more exercise. 

Six months later, Kevin returned to the clinic weighing nine pounds more than he had at the previous visit. When the new physician on duty asked if he had been able to make any of the lifestyle changes suggested by her colleague. Kevin told a story she had heard far too many times before. The first week after his last doctor's visit, Kevin had tried eliminating all of his favorite foods and snacks. He skipped breakfast, drank a meal replacement shake for lunch and ate a calorie reduced frozen dinner in the evening. He had also tried to eliminate the fat in his diet. The first week, Kevin lost four pounds but as the weeks went on he found it impossible to stick to this planed restrictive diet and he noticed that he was replacing his favourite high fat foods like potato chips and pizza with foods that were high in sugar. In the evening he would find himself in front of the television, snacking on multiple packages of Swedish fish. By the time he went to bed, he would almost always feel he had over eaten. The soda machine at work became his enemy as he tried unsuccessfully to walk by without buying the cold soda cans that he ended up drinking usually three or four times a day. 

He and his wife both worked long hours so one of them would usually stops for take outs on the way and they would end up sharing a pizza and a two liter of Coke, exhausted from their long days of work. Regular exercise was difficult for Kevin because of his joint pain and he often felt that he just didn't have the energy to move. 

The physician took notes and asked clarifying questions as Kevin spoke. Identifying major target areas for change. Including specific food and eating behaviors that were contributing to Kevin's uphill battle with his weight. She asses Kevin readiness to make dietary changes and asked if the couple had access to simple cooking tools like a pot, a knife and a cutting board. Then she spoke with Kevin and his wife about the importance of avoiding highly processed foods in order to achieve their health goals for Kevin. 

Together, they came up with a stepwise action plan that would allow them to gradually reallocate a small amount of time to the preparation of simple, home cooked meals. In this way they could once again be in control of the fat, sugar, salt, and total calories they were consuming. Kevin and his wife enrolled in a free online nutrition and cooking course and began tracking their food intake using an online food blog. To help them control portion sizes, their physician advised them to buy a set of affordable smaller dinner plates and glasses that they found at a local hardware store. The couple kept their meals simple, but made sure that each plate was composed of one-half plant-based foods like fruits and vegetables. WIth the other half of the meal made up of lean protein and whole grain carbohydrates. 

Over the next four weeks, they gradually began to feel more comfortable in the kitchen. Kevin tried his hand at making veggie omelets and a stir fry and even a homemade tomato sauce. He started to feel pretty good about the food that he was able to prepare at home. On Sundays when they had more time, Kevin's wife would cook a stew or a pot of vegetable soup and freeze these meals in smaller containers for later on in the week. 

Following his action plan, Kevin gradually replaced the sodas he once drank daily with unsweetened sparkling water. Six months later, and with regular follow up visits, Kevin's weight had dropped to 165 pounds. 

And his joints were no longer hurting him, allowing him to start walking regularly. His fasting blood sugar level and his lipid profile had both improved. And he told his physician that he had more energy and was actually enjoying his food more now because he no longer felt guilty about his poor eating habits. He and his wife found that they talked more now that they were spending a bit more time in the kitchen together after work. They sat down for meals together and made a pact to stop snacking in front of the TV. 

They even found their new eating habits to be more economical because they shopped for groceries once or twice a week instead of buying each meal separately, and usually buying more food than they needed. 18 months later, Kevin had managed to keep the weight off and his fasting blood sugar had returned to normal. 

Kevin told his physician that he felt better at he age of 49 than he had at 39. Life as a healthy middle age man was treating him well and he couldn't imagine ever going back. 

* A Step-wise Approach to Behavior Change

Many people struggle to get started when they're told they need to improve their eating habits. Here are some tips that can help you achieve sustainable positive change. Firstly, it's important to take a stepwise approach to making dietary changes. One or two small changes each week will lead to more sustainable change, than trying to make many drastic changes all at once. Identify target areas for change like times of day that are particularly challenging for you, or situations in which you tend to overeat. This can help you to define those stepwise changes and to come with an action plan. For example, in week 1 you might decide to replace all of the sweetened beverages in the fridge with unsweetened sparkling water. You might even find creative ways to remind yourself of this change by brushing and flossing your teeth soon after dinner. Additional goals added in the second week might include bringing a home made lunch to work instead of grabbing a hot dog from the vendor down the street. And replacing the high calorie, heavily processed snack foods in the home with fresh fruits and crisp vegetables and maybe a healthy dip. Later on, you might choose to avoid meat on one or two days of the week and instead eat plant-based proteins like beans or lentils on those days. 

Behavioral changes alone can be an important part of the step wise action plan. They can facilitate weight control even without consciously changing the foods you eat. If you like the idea of focusing on behavioral strategies, try signing a contract with yourself stating that for the next month you will only eat when your seated at a table using cutlery and a plate. This change alone, increases the likely hood that the foods you eat will be well thought out rather than impulse foods. A similar behavioral change is the decision to cook at home twice, three times or maybe even every night of the week. The chance of those foods being healthier than what you ate before are pretty high. 

Sustainable dietary improvements require a realistic targeted approach that focuses on progressive improvements in your diet without the fear of failure that comes when you try to achieve unrealistic dietary goals. Food is one of the greatest joys of life, and optimizing your health means identifying the foods and eating behaviors that will satisfy you while protecting your long term health. 
