
patch:
	cp ../week-02/ML_Octave_400_patch/lib/makeValidFieldName.m machine-learning-ex*/ex*/lib/
	cp ../week-02/ML_Octave_400_patch/lib/jsonlab/loadjson.m machine-learning-ex*/ex*/lib/jsonlab
	cp ../week-02/ML_Octave_400_patch/lib/xxNumToHexStr.m machine-learning-ex*/ex*/lib/
